### ISSUE TITLE
feat: make postCheck hook required

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-ops#152]
Currently the default `_postCheck` hook just logs a warning, to encourage people to implement it when creating tasks (example [here](https://github.com/ethereum-optimism/superchain-ops/blob/651056909a606e0f6a2b7bdbaf9e61ff1c67e002/script/SignFromJson.s.sol#L39)). It would be ideal to have a `require(false, "_postCheck not implemented")` instead to force an implementation.

However, this is not currently implemented because it breaks the `sc_rehearsal_1`, `sc_rehearsal_2`, and `sc_rehearsal_4` tasks which we want to keep in CI. Therefore the scope of this issue is:
1. Give those tasks their own local solidity file, and have them implement an empty post-check.
2. Change all `_postCheck` hooks to have a reverting, default implementation (using `require(false)` because this prevents solidity from emitting "unreachable code" warnings)

**Comment by ShubhSensei** [comment]
May I work on this issue?

**Comment by ShubhSensei** [comment]
I'm unable to push my code on GitHub in optimism-superchain-ops repo. What should I do? 

![image0.png](https://github.com/ethereum-optimism/superchain-ops/assets/91625601/cca89665-52f0-4552-bc4a-774dab4fb55e)

**Comment by mds1** [comment]
This was completed by https://github.com/ethereum-optimism/superchain-ops/pull/266, thank you @ShubhSensei!
