### ISSUE TITLE
Forked Network Tests

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/superchain-ops#18]
Having tests against a forked network would be very helpful for ensuring that any spell is correct. 

The forge scripting framework that we are using has a convenience `_postCheck` [method](https://github.com/base-org/contracts/blob/e961e8638874d571aa63a6e35507e3779131d1eb/script/universal/MultisigBuilder.sol#L23) that can be implemented with assertions about the upgrade. Each script should implement the `_postCheck` method with application specific assertions and should be ran before performing an upgrade.

There are 2 options for how these tests can be implemented:
- Spin up anvil and run the script exactly as is against a forked network. This may not work ideally with multisigs unless coupled with the RPC `hardhat_setStorageAt` (there is also an anvil prefixed alias) to overwrite the signer threshold.
- Do all of the execution in memory as a simulation, so call the forge script without the `--broadcast` flag, pin the command to a particular blocknumber and pass a URL to fork state from. We would want to make a solidity library that can be used for overwriting the signer threshold, this is easy to do with the cheatcode `vm.store`.

The second option seems a bit easier to me.

The `justfile` could be updated with a `test` command that CI can consume. We could choose to stop running tests for upgrades that we have already performed after some time if we wanted to.

We may also want to consider if we want to have a `_preCheck` function that can be implemented as well.

**Comment by mds1** [comment]
@tynes What exactly did you have in mind for this issue's scope? Should this be closed because we do implement the postCheck hooks now, or did you mean running the standard monorepo test suite against the state resulting from a task?

**Comment by tynes** [comment]
Good to close this based on the post hooks existing
