### ISSUE TITLE
doc: update `PRESIGNED-PAUSE.md` to explain all state overrides

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-ops#221]
The current presigned pause docs do not explain all state overrides. From https://github.com/ethereum-optimism/superchain-ops/pull/220#discussion_r1626540464:

> > You will see a state override (not a state change). This is expected and its purpose is to generate a successful Safe execution simulation without collecting any signatures.
> 
> This is what `PRESIGNED-PAUSE.md` says, but there are 4 overrides

**Comment by ShubhSensei** [comment]
Can I work on this issue?

**Comment by mds1** [comment]
Ah, this documentation is actually up to date now and was fixed in the original PR. Future presigned pauses will only need 1 state override as currently listed in `PRESIGNED-PAUSE.md`
