### ISSUE TITLE
Duplicate signatures in nested approval call

### ISSUE THREAD

**Issue by sebastianst** [ethereum-optimism/superchain-ops#267]
The execution of the `approve foundation` call for the Fjord-related `DGF.setImplementation` task had a duplicate signature in it, causing the call to revert. @zchn fixed it by manually removing the duplicate signature from the array and then manually crafting and sending the transaction from one of his 1-1 multisigs.

The input `SIGNATURES` env var array had a pre-approved signature in it, which probably caused the duplication.

**Comment by mds1** [comment]
Problem:
- In the [base-org/contracts repo](https://github.com/base-org/contracts), in the [`approve`](https://github.com/base-org/contracts/blob/c14278a67d6eb029d3b9b505eea67d2b2ea637af/script/universal/NestedMultisigBuilder.sol#L104-L124) method in `script/universal/NestedMultisigBuilder.sol`
- We always concatenate the given `_signatures` with the `prevalidatedSignatures(approvers)`, even if the given signatures include a prevalidate signature, resulting in the transaction reverting

Solution:
- A PR into the `base-org/contracts` repo that first fetches all prevalidated signatures first.
- Compares each against all provided signatures, and filter out duplicates.
- A test showing this new functionality works as expected. I don't think NestedMultisigBuilder has any tests in the Base repo, so a new test file will need to be added

**Comment by cpp-phoenix** [comment]
Hi, I am working on it

**Comment by cpp-phoenix** [comment]
Kindly review: https://github.com/base-org/contracts/pull/94

**Comment by mdehoog** [comment]
Proposing a slightly simpler fix here: https://github.com/base-org/contracts/pull/95

**Comment by mds1** [comment]
I see https://github.com/base-org/contracts/pull/95 was merged, so closing this as completed. Thank you both!
