### ISSUE TITLE
Nonce overrides not picked up in nested ceremony

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/superchain-ops#328]
In the 018 ceremony, the Foundation [nonce override](https://github.com/ethereum-optimism/superchain-ops/blob/main/tasks/eth/018-granite-upgrade/.env#L9) was not respected. 

The signers who signed after the 016 ceremony were unaffected, as the actual nonce matched the setting in the `.env` file (`7`), however those who signed earlier, signed on the current nonce at the time (`6`).

Here is output from one signer at the time, which shows the correct nonces, but crucially does not include [this line](https://github.com/base-org/contracts/blob/main/script/universal/NestedMultisigBuilder.sol#L67): `Creating transaction with nonce:`.

```
== Logs ==
  Reading transaction bundle /Users/k/Projects/work/superchain-ops/tasks/eth/018-granite-upgrade/input.json
  Safe 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A current nonce: 5
  Safe 0x847B5c174615B1B7fDF770882256e2D3E95b9D92 current nonce: 7
  Safe 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A current nonce: 5
  ---
Nested hash:
  0x09fd703ab1d8117f8436d4d43e921136a28fd49fb439f37ef991a0249f6045b0
  Safe 0x847B5c174615B1B7fDF770882256e2D3E95b9D92 current nonce: 7
  ---
If submitting onchain, call Safe.approveHash on 0x847B5c174615B1B7fDF770882256e2D3E95b9D92 with the following hash:
  0xb0fd1c9e0540bd6ae27151cf9c497d8bb4f1fd1710e3516f6e2eaf5e0e8908ad
  Safe 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A current nonce: 5
  Safe 0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A current nonce: 5
  Safe 0x847B5c174615B1B7fDF770882256e2D3E95b9D92 current nonce: 7
```

## Repro

This can be repro'd with the following steps:

1. `cd tasks/eth/018-granite-upgrade`
2. Edit the `.env` file to update `SAFE_NONCE_0X847B5c174615B1B7fDF770882256e2D3E95b9D92=9` (or any value other than the current nonce.
3. run 
  ```
  SIMULATE_WITHOUT_LEDGER=1 just \
   --dotenv-path $(pwd)/.env \
   --justfile ../../../nested.just \
   simulate foundation
   ```

**Comment by maurelian** [comment]
by removing the `try` and just nakedly calling `vm.envUint` [here](https://github.com/base-org/contracts/blob/main/script/universal/NestedMultisigBuilder.sol#L67), we get: 

```
VM::envUint("SAFE_NONCE_0X5A0AAE59D09FCCBDDB6C6CCEB07B7279367C3D2A") [staticcall]
   └─ ← [Revert] vm.envUint: environment variable "SAFE_NONCE_0X5A0AAE59D09FCCBDDB6C6CCEB07B7279367C3D2A" not found
```

**Comment by mds1** [comment]
This is because the `SAFE_NONCE_0X847B5c174615B1B7fDF770882256e2D3E95b9D92` env var has lowercase letters, but it needs to be all caps. We should add a CI check that env vars of this format use all caps
