### ISSUE TITLE
`PostChecks()` are executed on the `approve` feature

### ISSUE THREAD

**Issue by Ethnical** [ethereum-optimism/superchain-ops#361]
When using the nested Justfile `nested.just`, the feature `approve` is used to create the `approveHash` and later on execute the task.
However, a bug occurs when using `approve` on the task. This will go through the `postChecks()` to ensure all the state changes are as expected.
However, no state changes are expected during this `approve` method. Thus, causing the command to **fail** as the check will not be met correctly.
A workaround solution is to comment out the checks inside the `approve` function into the just file `nested.just`.

**Comment by TheMarvelFan** [comment]
Hi @Ethnical ,

I would like to work on this issue if no one already is.

Thanks!

**Comment by mds1** [comment]
Hey @TheMarvelFan, thanks for your interest! This was actually completed by #353, so I will close this issue
