### ISSUE TITLE
Automating Superchain-ops Upgrade Execution Safety

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/superchain-ops#37]
## Goals:

Improve the safety and ergonomics of L1 on-chain actions by:

1. checking the full set of state accesses and changes
2. checking the post action state of the system

## Non Goals:

- Implementing this functionality for L2 upgrades

### Enabling L1 upgrade safety while maintaining flexibility in the tooling of the repo

This work will introduce a new contract `L1SignJson`, which inherits from `SignJson`.  The original `SignJson` contract will thus remain mostly unchanged and can be used in ceremonies that don't require or are not supported by the added checks.

### Superchain Registry access

In order to obtain the addresses of the system contracts required for this work, the Superchain Registry will be added as a submodule. The required commit of the superchain registry can be provided as an env var to ensure the right one is used.

The json utilities provided for forge-std will be used to parse this information. This is considered less error prone than providing the local address of the superchain registry.

### Post Checking

The ChainAssertions library will be imported and the post checks will be called. These of course will not run on-chain, but will be executed during the pre-broadcast simulation.

### State diff checking

Ceremonies using this additional safety will require a new `diff.json` file. This file will provide an array of objects which correspond to the format of the state accesses struct returned by foundry's `vm.stopAndReturnStateDiff()`.

All diffs in the JSON file MUST be includes in the state diffs, and no state diffs will be allowed which are not included there.

An alternative to the `diff.json` file may be to define the state diffs in a `Diff.sol`. This option will be explored during implementation.

**Comment by mds1** [comment]
I'm going to close this issue as completed:
- We do have the superchain registry as a dependency and use it to getch addresses
- We do have post check hooks used to make assertions
- We do not yet have state diff checking, but as part of a separate issue we will think about how to do that
